export interface CommunityResident {
    buildingUuid: string;
    byDate: null;
    byStatus: null;
    cardNums: null | string;
    cardSyn: null;
    carNum: null;
    communityUuid: number;
    companyUuid: null;
    createTime: string;
    createUser: number;
    createUserName: string;
    description: null | string;
    duty: null;
    education: null | string;
    emergencyContact: null;
    emergencyContactPhone: null | string;
    epidemicUuid: null;
    expireTime: null;
    fixedPhone: null;
    goodPartyMember: null | string;
    householdRegistration: null;
    housesAddress: string;
    housesUuid: number;
    idArea: null;
    idNumber: null | string;
    idType: number;
    isAuthentication: number;
    isBangMember: null;
    isChinaMobile: number;
    isDefault: number;
    isDelete: number;
    isolateAddr: null;
    isolateEndDate: null;
    isolateStartDate: null;
    isPartyMember: number;
    isUploadTemp: null;
    leaseEndDate: null;
    leaseStartDate: null;
    libraryUrl: null;
    localRegister: null;
    loveNames: null;
    loveNamesList: string[];
    lovepartyMember: null;
    mark: null;
    mobile: string;
    name: string;
    nucleicList: null;
    partyMemberPhoto: null;
    picUrl: null | string;
    provinceName: null;
    queryKey: null;
    registrantIdentity: number | null;
    registrationMethod: number | null;
    residentavatar: null;
    residentLabel: null;
    residentRole: number;
    residentUuid: null;
    sex: number;
    status: null;
    updateTime: string;
    updateUser: number;
    updateUserName: null | string;
    uploadTempFreq: null;
    upUuid: null;
    usimCard: string;
    uuid: number;
}