/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Layout: typeof import('../views/Layout.vueault']
    Menu: typeof import('./../components/Menu.vue')['default']
    Navigator1: typeof import('./../components/Navigator1.vue')['default']
    Navigator2: typeof import('./../components/Navigator2.vue')['default']
    Navigator3: typeof import('./../components/Navigator3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
